ci: update tag.yml

diff --git a/.github/workflows/tag.yml b/.github/workflows/tag.yml
--- a/.github/workflows/tag.yml
+++ b/.github/workflows/tag.yml
@@ -28,6 +28,16 @@ jobs:
           VERSION=$(jq -r .version ./src/Packages/Passport/package.json)
           echo "VERSION=$VERSION" >> "$GITHUB_ENV"
 
+      - name: Check TS SDK version exists in index.html
+        id: check_ts_sdk_version
+        run: |
+          version=$(grep -oP '"x-sdk-version":"ts-immutable-sdk-\K[0-9]+\.[0-9]+\.[0-9]+' ./src/Packages/Passport/Runtime/Resources/index.html | head -n 1)
+
+          if [[ -z "$version" ]]; then
+            echo "Error: TS SDK version not found in index.html" >&2
+            exit 1
+          fi
+
       - name: Create Tag
         uses: negz/create-tag@v1
         with:
