fix: windows

diff --git a/.github/workflows/ui-tests.yml b/.github/workflows/ui-tests.yml
--- a/.github/workflows/ui-tests.yml
+++ b/.github/workflows/ui-tests.yml
@@ -132,14 +132,21 @@ jobs:
           MAILSLURP_API_KEY: ${{ secrets.MAILSLURP_API_KEY }}
         working-directory: sample/Tests
         run: |
-          echo "Current directory:"
-          pwd
-          echo "Listing contents:"
-          dir
-          echo "Python version:"
+          Write-Host "Current directory:"
+          Get-Location
+
+          Write-Host "Listing contents:"
+          Get-ChildItem
+
+          Write-Host "Python version:"
           python --version
-          echo "Running pytest:"
-          pytest -vv --tb=short test/test_windows.py::WindowsTest || (echo "Pytest failed with code $?" && exit 1)
+
+          Write-Host "Running pytest:"
+          pytest -vv --tb=short test/test_windows.py::WindowsTest
+          if ($LASTEXITCODE -ne 0) {
+            Write-Error "Pytest failed with code $LASTEXITCODE"
+            exit $LASTEXITCODE
+          }
         # run: ${{ matrix.test_script }}
       - name: Remove temporary keychain
         if: matrix.targetPlatform == 'StandaloneOSX' && (github.event_name != 'workflow_dispatch' || github.event.inputs.targetPlatform == 'All' || github.event.inputs.targetPlatform == 'StandaloneOSX')
